behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 12
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 6
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0 
    keep_checkpoints: 5
    max_steps: 8750000
    time_horizon: 1125
    summary_freq: 10750
    self_play:
      save_steps: 40000
      team_change: 150000
      swap_steps: 3400
      window: 8
      play_against_latest_model_ratio: 0.53
      initial_elo: 1200.00
