behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 512
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.0004
      epsilon: 0.4 
      lambd: .75
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000022
    time_horizon: 1001
    summary_freq: 20007
    self_play:
      save_steps: 60000
      team_change: 99998
      swap_steps: 10000
      window: 22
      play_against_latest_model_ratio: 0.8
      initial_elo: 1200.00
